### ISSUE TITLE
Diffable notebooks

### ISSUE THREAD

**Issue by wjchulme** [opensafely/research-template#17]
Add ability to use diffable notebooks and push to existing repos

**Comment by iaindillingham** [comment]
Diffable notebooks are hard and, I'd argue, not the solution. That said, tools such as [nbdime](https://nbdime.readthedocs.io/en/latest/) can help.

I said they're "not the solution", which is a bold claim given that I don't know the problem 🙂 However, I think the problem is that notebooks aren't good places to store analytic code: they work well for exploring and communicating, but work poorly for reasoning. [Cookiecutter Data Science](https://drivendata.github.io/cookiecutter-data-science/#notebooks-are-for-exploration-and-communication) suggest that after we've explored, we move analytic code to a Python module, where it can be tested. Python modules are much easier to diff, too.
